Update pterodactyl_update

diff --git a/pterodactyl_update b/pterodactyl_update
--- a/pterodactyl_update
+++ b/pterodactyl_update
@@ -10,15 +10,8 @@
 touch ${HOME}/ptero_logs.txt
 cd /var/www/pterodactyl
 
-php artisan down
+php artisan down || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
 # Dependency, if last command didnt work then echo reason for failure in log file
-if [ $? -eq 0 ]
-  then 
-  echo "artisan down"
-  else
-  echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
-  exit
-fi
 
 curl -L https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz | tar -xzv
 chmod -R 755 storage/* bootstrap/cache
@@ -28,51 +21,16 @@ php artisan config:clear
 php artisan migrate --seed --force
 chown -R www-data:www-data /var/www/pterodactyl/*
 
-php artisan queue:restart
+php artisan queue:restart || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
 # Dependency, if last command didnt work then echo reason for failure in log file
-if
-  [ $? -eq 0 ]
-  then 
-  echo "artisan restarted"
-  else
-  echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
-  exit
-fi
 
-php artisan up
-if
-# Dependency, if last command didnt work then echo reason for failure in log file
-  [ $? -eq 0 ]
-  then 
-  echo "artisan up"
-  else
-  echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
-  exit
-fi
+php artisan up || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
 
-systemctl stop wings
-if
-# Dependency, if last command didnt work then echo reason for failure in log file
-  [ $? -eq 0 ]
-  then 
-  echo "wings stopped"
-  else
-  echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
-  exit
-fi
+systemctl stop wings || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
 
 curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
 chmod u+x /usr/local/bin/wings
 
-systemctl restart wings
-if
-# Dependency, if last command didnt work then echo reason for failure in log file
-  [ $? -eq 0 ]
-  then 
-  echo "wings restarted"
-  else
-  echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
-  exit
-fi
+systemctl restart wings || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
 
 echo "Update finished successfully!"
