Update simple_docker-update

diff --git a/simple_docker-update b/simple_docker-update
--- a/simple_docker-update
+++ b/simple_docker-update
@@ -10,5 +10,14 @@ docker-compose down
 
 #pulling new images
 docker-compose pull
+if
+  [ $? -eq 0]
+then 
+  echo "pull successful"
+else
+  echo "$? failed"
+  exit
+fi
+
 docker-compose up -d
 echo "docker update complete"
